DATASET_PATH: ./data/omniglot
NUM_CLASSES: 1623
N_WAY: 5
K_SHOT: 1
Q_QUERY: 15
EMBEDDING_DIM: 128
INPUT_SIZE: 36
TRANSFORMER_LAYERS: 2
TRANSFORMER_HEADS: 8
TRANSFORMER_DROPOUT: 0.1
EPOCHS: 100
LEARNING_RATE: 0.0005
BATCH_SIZE: 16
WEIGHT_DECAY: 0.0001
GRADIENT_ACCUMULATION_STEPS: 1
LABEL_SMOOTHING: 0.1
USE_MIXED_PRECISION: True
CHECKPOINT_DIR: ./checkpoints
LOGS_DIR: ./logs
CHECKPOINT_PATH: ./checkpoints/best_model.pth
TENSORBOARD_LOG_DIR: ./logs
USE_DATA_AUGMENTATION: rand # False, 'rand', 'trivial'
USE_LR_SCHEDULER: onecylcle # 'plateau', 'cosine', 'onecycle', False
USE_TENSORBOARD: True
USE_GRADIENT_CLIPPING: True
GRADIENT_CLIP_VALUE: 1.0
USE_EARLY_STOPPING: True
EARLY_STOPPING_PATIENCE: 20
USE_WANDB: False
SEED: 42
OPTIMIZER: 'adamw' #adamw or sgd
META_LEARNING_ALGO: 'maml' # 'protonet', 'maml', 'reptile'